export const AUTH_LOGGED_SUCCESSFULLY = 'LOGGED_SUCCESSFULLY'
export const AUTH_LOGGED_FAILED = 'LOGGED_FAILED'
export const AUTH_LOGOUT = 'LOGOUT'
export const AUTH_LOGGING_ATTEMPT = 'LOGGING_ATTEMPT'